/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchInstanceRequest {
    #[serde(rename = "snapshot_metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub snapshot_metadata: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "instance_metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instance_metadata: Option<Option<Box<models::InstanceMetadata>>>,
}

impl BranchInstanceRequest {
    pub fn new() -> BranchInstanceRequest {
        BranchInstanceRequest {
            snapshot_metadata: None,
            instance_metadata: None,
        }
    }
}

