/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchInstanceResponse {
    #[serde(rename = "snapshot")]
    pub snapshot: Box<models::SnapshotModel>,
    #[serde(rename = "instances")]
    pub instances: Vec<models::InstanceModel>,
}

impl BranchInstanceResponse {
    pub fn new(snapshot: models::SnapshotModel, instances: Vec<models::InstanceModel>) -> BranchInstanceResponse {
        BranchInstanceResponse {
            snapshot: Box::new(snapshot),
            instances,
        }
    }
}

