/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "key_prefix")]
    pub key_prefix: String,
    #[serde(rename = "created")]
    pub created: i32,
}

impl CreateApiKeyResponse {
    pub fn new(id: String, key: String, key_prefix: String, created: i32) -> CreateApiKeyResponse {
        CreateApiKeyResponse {
            id,
            key,
            key_prefix,
            created,
        }
    }
}

