/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecRequest {
    #[serde(rename = "command")]
    pub command: Vec<String>,
}

impl ExecRequest {
    pub fn new(command: Vec<String>) -> ExecRequest {
        ExecRequest {
            command,
        }
    }
}

