/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecResponse {
    #[serde(rename = "stdout")]
    pub stdout: String,
    #[serde(rename = "stderr")]
    pub stderr: String,
    #[serde(rename = "exit_code")]
    pub exit_code: i32,
}

impl ExecResponse {
    pub fn new(stdout: String, stderr: String, exit_code: i32) -> ExecResponse {
        ExecResponse {
            stdout,
            stderr,
            exit_code,
        }
    }
}

