/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExposeHttpServiceRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "auth_mode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_mode: Option<Option<models::HttpServiceAuthMode>>,
}

impl ExposeHttpServiceRequest {
    pub fn new(name: String, port: i32) -> ExposeHttpServiceRequest {
        ExposeHttpServiceRequest {
            name,
            port,
            auth_mode: None,
        }
    }
}

