/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpServiceAuthMode {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "api_key")]
    ApiKey,

}

impl std::fmt::Display for HttpServiceAuthMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::ApiKey => write!(f, "api_key"),
        }
    }
}

impl Default for HttpServiceAuthMode {
    fn default() -> HttpServiceAuthMode {
        Self::None
    }
}

