/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceMetadata : Metadata for the new instances. If a list is provided, each instance will have the corresponding metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceMetadata {
}

impl InstanceMetadata {
    /// Metadata for the new instances. If a list is provided, each instance will have the corresponding metadata.
    pub fn new() -> InstanceMetadata {
        InstanceMetadata {
        }
    }
}

