/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceSshKey {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "private_key")]
    pub private_key: String,
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl InstanceSshKey {
    pub fn new(private_key: String, public_key: String, password: String) -> InstanceSshKey {
        InstanceSshKey {
            object: None,
            private_key,
            public_key,
            password,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "instance_ssh_key")]
    InstanceSshKey,
}

impl Default for Object {
    fn default() -> Object {
        Self::InstanceSshKey
    }
}

