/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceRefs {
    #[serde(rename = "snapshot_id")]
    pub snapshot_id: String,
    #[serde(rename = "image_id")]
    pub image_id: String,
}

impl InstanceRefs {
    pub fn new(snapshot_id: String, image_id: String) -> InstanceRefs {
        InstanceRefs {
            snapshot_id,
            image_id,
        }
    }
}

