/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstanceExpireAction {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "pause")]
    Pause,

}

impl std::fmt::Display for InstanceExpireAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stop => write!(f, "stop"),
            Self::Pause => write!(f, "pause"),
        }
    }
}

impl Default for InstanceExpireAction {
    fn default() -> InstanceExpireAction {
        Self::Stop
    }
}

