/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceSpec {
    /// VCPU Count of the snaphshot
    #[serde(rename = "vcpus")]
    pub vcpus: i32,
    /// Memory of the snaphshot in megabytes
    #[serde(rename = "memory")]
    pub memory: i32,
    /// Size of the snapshot in megabytes
    #[serde(rename = "disk_size")]
    pub disk_size: i32,
}

impl ResourceSpec {
    pub fn new(vcpus: i32, memory: i32, disk_size: i32) -> ResourceSpec {
        ResourceSpec {
            vcpus,
            memory,
            disk_size,
        }
    }
}

