/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotRefs {
    #[serde(rename = "image_id")]
    pub image_id: String,
}

impl SnapshotRefs {
    pub fn new(image_id: String) -> SnapshotRefs {
        SnapshotRefs {
            image_id,
        }
    }
}

