/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSshKeyRequest {
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl UpdateSshKeyRequest {
    pub fn new(public_key: String) -> UpdateSshKeyRequest {
        UpdateSshKeyRequest {
            public_key,
        }
    }
}

