/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSshKeyModel {
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "created")]
    pub created: i32,
}

impl UserSshKeyModel {
    pub fn new(public_key: String, created: i32) -> UserSshKeyModel {
        UserSshKeyModel {
            public_key,
            created,
        }
    }
}

