/*
 * MorphVM API
 *
 * REST API for managing MorphVM instances and snapshots.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInstanceUsageModel {
    #[serde(rename = "instance_cpu_time")]
    pub instance_cpu_time: i32,
    #[serde(rename = "instance_memory_time")]
    pub instance_memory_time: i32,
    #[serde(rename = "instance_disk_time")]
    pub instance_disk_time: i32,
    #[serde(rename = "period_start")]
    pub period_start: i32,
    #[serde(rename = "period_end")]
    pub period_end: i32,
}

impl UserInstanceUsageModel {
    pub fn new(instance_cpu_time: i32, instance_memory_time: i32, instance_disk_time: i32, period_start: i32, period_end: i32) -> UserInstanceUsageModel {
        UserInstanceUsageModel {
            instance_cpu_time,
            instance_memory_time,
            instance_disk_time,
            period_start,
            period_end,
        }
    }
}

